Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.
Set Bullet Behavior "Strict Subproofs".

Set Printing Implicit.

Require Import concrete.int_32.
Require Import symbolic.symbolic symbolic.int_32 symbolic.exec.
Require Import compartmentalization.common compartmentalization.symbolic.

(* The only reason I am so explicit here is that this will be used from Haskell,
   where the exact instances must sometimes be inserted by hand.  By being
   explicit here, I can avoid any unpleasant surprises.  Of course, this was
   generated by inspecting the auto-type-class-instantiated original of `stepf
   Sym.syscalls`. *)

Definition step_compartmentalized
             (syscalls : compartmentalization_syscall_addrs concrete_int_32_mt)
             :  Symbolic.state concrete_int_32_mt
             -> option (Symbolic.state concrete_int_32_mt)
  := stepf (mt    := concrete_int_32_mt)
           (ops   := concrete_int_32_ops)
           (sp    := Sym.sym_compartmentalization (mt := concrete_int_32_mt))
           (Sym.syscalls (mt           := concrete_int_32_mt)
                         (ops          := concrete_int_32_ops)
                         (scr          := concrete_int_32_scr)
                         (cmp_syscalls := syscalls)).

